// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIlZYt0XZPBusqBP3cwQLbloDn-acoSQM',
    appId: '1:119615536254:web:c63c9fff10b483fa33ec2f',
    messagingSenderId: '119615536254',
    projectId: 'gmr-fruits-ecommerce',
    authDomain: 'gmr-fruits-ecommerce.firebaseapp.com',
    storageBucket: 'gmr-fruits-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9_yxnJeVvfQwPcFyz7h6R-crd5YcgDg',
    appId: '1:119615536254:android:f89f934df9575c8c33ec2f',
    messagingSenderId: '119615536254',
    projectId: 'gmr-fruits-ecommerce',
    storageBucket: 'gmr-fruits-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhm7mgtIuuxumXNrMa2cbAQjST5YHhrTc',
    appId: '1:119615536254:ios:79434bac5ebf20d033ec2f',
    messagingSenderId: '119615536254',
    projectId: 'gmr-fruits-ecommerce',
    storageBucket: 'gmr-fruits-ecommerce.appspot.com',
    iosClientId:
        '119615536254-99nmfttphobmvor4kj3rm9r3lbn9vt6i.apps.googleusercontent.com',
    iosBundleId: 'com.gmr.fruit_ecommerce',
  );
}
